; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:attiny85]
platform = atmelavr
board = digispark-tiny
framework = arduino

# Important note:
# If you get an error about usbdrvasm.asm:21: Error: unknown opcode `end'
# This is because this file is made for IAR compiler, not for avr-gcc.
# To fix this, the only solution for now is to delete this file.
